name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Test Frontend
    - run: |
        cd frontend
        npm ci
        npm run build --if-present
        npm test
